[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#f0f6fc"
font = "sans serif"

[client]
maxUploadSize = 200

[logger]
level = "warning"

[ui]
hideTopBar = false
hideFooter = false
